version: '3.4'


networks:
  moon-cloud:
    external: true

services: 
  zoonavigator:
    container_name: zoonavigator
    networks:
      - default
      - moon-cloud
    # name: moon-elasticsearch
    restart: always
    hostname: zoonavigator
    image: "elkozmon/zoonavigator:latest"
    environment:
      - HTTP_PORT=9010
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9002:9010"

