version: '3.4'

networks:
  moon-cloud:
    external: true

services: 
  moonapp3_1:
    networks:
      - default
      - moon-cloud
    container_name: moonapp3_1
    hostname: moonapp3_1
    restart: always
    build: ./moon-app3
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8030:7001"