version: '3.4'
networks:
  moon-cloud:
    external: true
services: 
  redis:
    networks:
      - default
      - moon-cloud
    container_name: redis
    restart: always
    image: 'redis:latest'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16379:6379"
    volumes:
      - ./redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime

  mysql:
    networks:
      - default
      - moon-cloud
    restart: always
    image: mysql:5.7.18
    container_name: mysql
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - /etc/localtime:/etc/localtime
    environment:
      - "MYSQL_ROOT_PASSWORD=Mo0n1234"
      - "MYSQL_DATABASE=moon"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 13306:3306
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
