version: '3.4'

networks:
  moon-cloud:
    external: true

services: 
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    hostname: rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
      - 5672:5672
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default
      - moon-cloud
