version: '3.4'

networks:
  moon-cloud:
    external: true

services: 
  moonapp1_1:
    networks:
      - default
      - moon-cloud
    container_name: moonapp1
    hostname: moonapp1
    restart: always
    build: ./moon-app1
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8010:7001"
