version: "3.1"

networks:
  app_net_1:
    external: true
services:
  moon-app1:
    networks:
      - default
      - app_net_1
    hostname: moon-app1
    restart: always
    build: .
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8011:7001"
